import "@/config/env";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { useShortcuts } from "../hooks/useShortcuts";

// subsets: ["latin"] restricts glyph maps to Latin characters only,
// avoiding loading Cyrillic/Greek/CJK blocks and reducing CSS payload.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "optional",
});

// Single variable font asset covers all app text weights; monospace utilities
// are mapped to this same face in globals.css to avoid a second font payload.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  const { HelpModal } = useShortcuts({});
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        {HelpModal}
      </body>
    </html>
  );
}
